name: Create a kind cluster

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - master

jobs:
  build:
    name: Create a kind cluster
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up kind cluster
        run: |
          chmod +x ./create_cluster.sh
          ./create_cluster.sh

      - name: Verify kind cluster
        run: |
          kubectl cluster-info
          kubectl get nodes